// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Probability',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'probability' }],
    },
    //{
    //  type: 'category',
    //  label: 'Brainteasers',
    //  collapsed: false,
    //  items: [{ type: 'autogenerated', dirName: 'brainteasers' }],
    //},
    //{
    //  type: 'category',
    //  label: 'Math',
    //  collapsed: false,
    //  items: [{ type: 'autogenerated', dirName: 'math' }],
    //},
  ],
};

export default sidebars;