// @ts-check

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Quant Questions',
      items: [
        {
          type: 'autogenerated',
          dirName: 'questions', // 自动加载 docs/questions
        },
      ],
    },
    {
      type: 'category',
      label: 'Learning',
      items: [
        {
          type: 'autogenerated',
          dirName: 'learning', // 自动加载 docs/learning
        },
      ],
    },
  ],
};

export default sidebars;